# Generated by Django 6.1 on 2026-08-20 09:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDictionary',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('barcode', models.CharField(max_length=50, null=True)),
                ('icon_number', models.IntegerField()),
                ('kcal', models.IntegerField(null=True)),
                ('proteins', models.FloatField(null=True)),
                ('fats', models.FloatField(null=True)),
                ('nutriscore', models.CharField(max_length=1)),
                ('is_global', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=45, unique=True)),
                ('status', models.CharField(choices=[('GLOBAL', 'GLOBAL'), ('PRIVATE', 'PRIVATE'), ('PENDING', 'PENDING')], default='GLOBAL', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('description', models.TextField(null=True)),
                ('calories', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('prep_time', models.TimeField()),
                ('is_global', models.BooleanField(default=True)),
                ('thumbnail', models.ImageField(null=True, upload_to='recipes/thumbnails')),
                ('item_status', models.CharField(choices=[('GLOBAL', 'GLOBAL'), ('PRIVATE', 'PRIVATE'), ('PENDING', 'PENDING')], default='GLOBAL', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=45, unique=True)),
                ('is_global', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=15, unique=True)),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('role', models.CharField(choices=[('USER', 'USER'), ('ADMIN', 'ADMIN')], default='USER', max_length=10)),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('DELETED', 'DELETED')], default='ACTIVE', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('order', models.IntegerField()),
                ('name', models.CharField(max_length=45)),
                ('picture', models.ImageField(null=True, upload_to='recipes/pictures')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SmartFridgeApp.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingListItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.FloatField()),
                ('is_done', models.BooleanField(default=False)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SmartFridgeApp.productdictionary')),
                ('shoppingList', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SmartFridgeApp.shoppinglist')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='SmartFridgeApp.unit')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeProduct',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.FloatField(validators=[django.core.validators.MinValueValidator(0.01)])),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='SmartFridgeApp.productdictionary')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SmartFridgeApp.recipe')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='SmartFridgeApp.unit')),
            ],
        ),
        migrations.AddField(
            model_name='unit',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SmartFridgeApp.user'),
        ),
        migrations.AddField(
            model_name='shoppinglist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='SmartFridgeApp.user'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='SmartFridgeApp.user'),
        ),
        migrations.AddField(
            model_name='productdictionary',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SmartFridgeApp.user'),
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('key', models.CharField(max_length=255, unique=True)),
                ('users', models.ManyToManyField(related_name='areas', to='SmartFridgeApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserProduct',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('expiration_date', models.DateField(null=True)),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0.01)])),
                ('added_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SmartFridgeApp.area')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SmartFridgeApp.productdictionary')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='SmartFridgeApp.unit')),
            ],
        ),
    ]
