# Generated by Django 6.1 on 2026-09-15 10:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartFridgeApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_areas', to=settings.AUTH_USER_MODEL),
        ),
    ]
