# Generated by Django 6.1 on 2026-08-20 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SmartFridgeApp', '0002_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='login',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
